# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'edumat.ui'
#
# Created: Sun May 16 18:39:23 2010
# by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

import os
class Ui_edumat(object):

    def closeall(self):
        os.system('killall python edumat.py')

    def sccanim(self):
        os.system('python x_scc_animated.py')

    def bccanim(self):
        os.system('python x_bcc_animated.py')

    def fccanim(self):
        os.system('python x_fcc_animated.py')

    def rollanim(self):
        os.system('python x_rolling.py')

    def fhmanim(self):
        os.system('python x_four_high_mill.py')

    def deanim(self):
        os.system('python x_extrusion.py')

    def ieanim(self):
        os.system('python x_back_extrusion.py')

    def fanim(self):
        os.system('python x_forging.py')

    def gsanim(self):
        os.system('python x_gating_system.py')

    def bfanim(self):
        os.system('python x_scc_animated.py')

    def sinanim(self):
        os.system('python x_scc_animated.py')

    def setupUi(self, edumat):
        edumat.setObjectName("edumat")
        edumat.resize(827, 641)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(edumat.sizePolicy().hasHeightForWidth())
        edumat.setSizePolicy(sizePolicy)
        edumat.setMinimumSize(QtCore.QSize(827, 641))
        edumat.setMaximumSize(QtCore.QSize(827, 641))
        edumat.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Normal,QtGui.QIcon.Off)
        edumat.setWindowIcon(icon)
        edumat.setAutoFillBackground(False)
        self.label = QtGui.QLabel(edumat)
        self.label.setGeometry(QtCore.QRect(110, 0, 541, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(14)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtGui.QFrame(edumat)
        self.line.setGeometry(QtCore.QRect(30, 30, 681, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtGui.QLabel(edumat)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_2 = QtGui.QFrame(edumat)
        self.line_2.setGeometry(QtCore.QRect(30, 70, 118, 3))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtGui.QFrame(edumat)
        self.line_3.setGeometry(QtCore.QRect(30, 70, 20, 121))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtGui.QLabel(edumat)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 56, 15))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.scc_tut = QtGui.QPushButton(edumat)
        self.scc_tut.setGeometry(QtCore.QRect(190, 80, 85, 27))
        self.scc_tut.setObjectName("scc_tut")
        self.scc_anim = QtGui.QPushButton(edumat)
        self.scc_anim.setGeometry(QtCore.QRect(280, 80, 85, 27))
        self.scc_anim.setObjectName("scc_anim")
        self.bcc_tut = QtGui.QPushButton(edumat)
        self.bcc_tut.setGeometry(QtCore.QRect(190, 120, 85, 27))
        self.bcc_tut.setObjectName("bcc_tut")
        self.fcc_tut = QtGui.QPushButton(edumat)
        self.fcc_tut.setGeometry(QtCore.QRect(190, 160, 85, 27))
        self.fcc_tut.setObjectName("fcc_tut")
        self.label_4 = QtGui.QLabel(edumat)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 56, 15))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(edumat)
        self.label_5.setGeometry(QtCore.QRect(60, 170, 56, 15))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.fcc_anim = QtGui.QPushButton(edumat)
        self.fcc_anim.setGeometry(QtCore.QRect(280, 160, 85, 27))
        self.fcc_anim.setObjectName("fcc_anim")
        self.bcc_anim = QtGui.QPushButton(edumat)
        self.bcc_anim.setGeometry(QtCore.QRect(280, 120, 85, 27))
        self.bcc_anim.setObjectName("bcc_anim")
        self.label_6 = QtGui.QLabel(edumat)
        self.label_6.setGeometry(QtCore.QRect(30, 200, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(edumat)
        self.label_7.setGeometry(QtCore.QRect(60, 240, 56, 15))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line_4 = QtGui.QFrame(edumat)
        self.line_4.setGeometry(QtCore.QRect(30, 210, 141, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_8 = QtGui.QLabel(edumat)
        self.label_8.setGeometry(QtCore.QRect(60, 280, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(edumat)
        self.label_9.setGeometry(QtCore.QRect(60, 320, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(edumat)
        self.label_10.setGeometry(QtCore.QRect(60, 360, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(edumat)
        self.label_11.setGeometry(QtCore.QRect(60, 400, 56, 15))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(edumat)
        self.label_12.setGeometry(QtCore.QRect(30, 430, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(edumat)
        self.label_13.setGeometry(QtCore.QRect(60, 470, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(edumat)
        self.label_14.setGeometry(QtCore.QRect(30, 510, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(edumat)
        self.label_15.setGeometry(QtCore.QRect(60, 550, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(edumat)
        self.label_16.setGeometry(QtCore.QRect(60, 590, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.line_5 = QtGui.QFrame(edumat)
        self.line_5.setGeometry(QtCore.QRect(30, 220, 20, 201))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.ie_tut = QtGui.QPushButton(edumat)
        self.ie_tut.setGeometry(QtCore.QRect(190, 350, 85, 27))
        self.ie_tut.setObjectName("ie_tut")
        self.de_tut = QtGui.QPushButton(edumat)
        self.de_tut.setGeometry(QtCore.QRect(190, 310, 85, 27))
        self.de_tut.setObjectName("de_tut")
        self.fhm_tut = QtGui.QPushButton(edumat)
        self.fhm_tut.setGeometry(QtCore.QRect(190, 270, 85, 27))
        self.fhm_tut.setObjectName("fhm_tut")
        self.roll_tut = QtGui.QPushButton(edumat)
        self.roll_tut.setGeometry(QtCore.QRect(190, 230, 85, 27))
        self.roll_tut.setObjectName("roll_tut")
        self.f_tut = QtGui.QPushButton(edumat)
        self.f_tut.setGeometry(QtCore.QRect(190, 390, 85, 27))
        self.f_tut.setObjectName("f_tut")
        self.line_6 = QtGui.QFrame(edumat)
        self.line_6.setGeometry(QtCore.QRect(30, 440, 141, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.line_6.setFont(font)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtGui.QFrame(edumat)
        self.line_7.setGeometry(QtCore.QRect(30, 520, 141, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtGui.QFrame(edumat)
        self.line_8.setGeometry(QtCore.QRect(30, 450, 20, 51))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtGui.QFrame(edumat)
        self.line_9.setGeometry(QtCore.QRect(30, 530, 20, 81))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gs_tut = QtGui.QPushButton(edumat)
        self.gs_tut.setGeometry(QtCore.QRect(190, 460, 85, 27))
        self.gs_tut.setObjectName("gs_tut")
        self.bf_tut = QtGui.QPushButton(edumat)
        self.bf_tut.setGeometry(QtCore.QRect(190, 540, 85, 27))
        self.bf_tut.setObjectName("bf_tut")
        self.sin_tut = QtGui.QPushButton(edumat)
        self.sin_tut.setGeometry(QtCore.QRect(190, 580, 85, 27))
        self.sin_tut.setObjectName("sin_tut")
        self.roll_anim = QtGui.QPushButton(edumat)
        self.roll_anim.setGeometry(QtCore.QRect(280, 230, 85, 27))
        self.roll_anim.setObjectName("roll_anim")
        self.fhm_anim = QtGui.QPushButton(edumat)
        self.fhm_anim.setGeometry(QtCore.QRect(280, 270, 85, 27))
        self.fhm_anim.setObjectName("fhm_anim")
        self.de_anim = QtGui.QPushButton(edumat)
        self.de_anim.setGeometry(QtCore.QRect(280, 310, 85, 27))
        self.de_anim.setObjectName("de_anim")
        self.ie_anim = QtGui.QPushButton(edumat)
        self.ie_anim.setGeometry(QtCore.QRect(280, 350, 85, 27))
        self.ie_anim.setObjectName("ie_anim")
        self.f_anim = QtGui.QPushButton(edumat)
        self.f_anim.setGeometry(QtCore.QRect(280, 390, 85, 27))
        self.f_anim.setObjectName("f_anim")
        self.gs_anim = QtGui.QPushButton(edumat)
        self.gs_anim.setGeometry(QtCore.QRect(280, 460, 85, 27))
        self.gs_anim.setObjectName("gs_anim")
        self.bf_anim = QtGui.QPushButton(edumat)
        self.bf_anim.setGeometry(QtCore.QRect(280, 540, 85, 27))
        self.bf_anim.setObjectName("bf_anim")
        self.sin_anim = QtGui.QPushButton(edumat)
        self.sin_anim.setGeometry(QtCore.QRect(280, 580, 85, 27))
        self.sin_anim.setObjectName("sin_anim")
        self.line_10 = QtGui.QFrame(edumat)
        self.line_10.setGeometry(QtCore.QRect(370, 70, 20, 541))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.marker = QtGui.QCheckBox(edumat)
        self.marker.setGeometry(QtCore.QRect(660, 60, 151, 20))
        self.marker.setObjectName("marker")
        self.textBrowser = QtGui.QTextBrowser(edumat)
        self.textBrowser.setGeometry(QtCore.QRect(400, 110, 411, 461))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setHtml("<img src=images/edumat.jpg></img>")
        self.leave = QtGui.QPushButton(edumat)
        self.leave.setGeometry(QtCore.QRect(700, 590, 111, 41))
        self.leave.setObjectName("leave")
        self.retranslateUi(edumat)
        QtCore.QObject.connect(self.leave, QtCore.SIGNAL("clicked()"), self.closeall)
        QtCore.QObject.connect(self.scc_tut, QtCore.SIGNAL("clicked()"), self.scctut)
        QtCore.QObject.connect(self.bcc_tut, QtCore.SIGNAL("clicked()"), self.bcctut)
        QtCore.QObject.connect(self.fcc_tut, QtCore.SIGNAL("clicked()"), self.fcctut)
        QtCore.QObject.connect(self.roll_tut, QtCore.SIGNAL("clicked()"), self.rolltut)
        QtCore.QObject.connect(self.fhm_tut, QtCore.SIGNAL("clicked()"), self.fhmtut)
        QtCore.QObject.connect(self.de_tut, QtCore.SIGNAL("clicked()"), self.detut)
        QtCore.QObject.connect(self.ie_tut, QtCore.SIGNAL("clicked()"), self.ietut)
        QtCore.QObject.connect(self.f_tut, QtCore.SIGNAL("clicked()"), self.ftut)
        QtCore.QObject.connect(self.gs_tut, QtCore.SIGNAL("clicked()"), self.gstut)
        QtCore.QObject.connect(self.bf_tut, QtCore.SIGNAL("clicked()"), self.bftut)
        QtCore.QObject.connect(self.sin_tut, QtCore.SIGNAL("clicked()"), self.sintut)
        QtCore.QObject.connect(self.scc_anim, QtCore.SIGNAL("clicked()"), self.sccanim)
        QtCore.QObject.connect(self.bcc_anim, QtCore.SIGNAL("clicked()"), self.bccanim)
        QtCore.QObject.connect(self.fcc_anim, QtCore.SIGNAL("clicked()"), self.fccanim)
        QtCore.QObject.connect(self.roll_anim, QtCore.SIGNAL("clicked()"), self.rollanim)
        QtCore.QObject.connect(self.fhm_anim, QtCore.SIGNAL("clicked()"), self.fhmanim)
        QtCore.QObject.connect(self.de_anim, QtCore.SIGNAL("clicked()"), self.deanim)
        QtCore.QObject.connect(self.ie_anim, QtCore.SIGNAL("clicked()"), self.ieanim)
        QtCore.QObject.connect(self.f_anim, QtCore.SIGNAL("clicked()"),self.fanim)
        QtCore.QObject.connect(self.gs_anim, QtCore.SIGNAL("clicked()"), self.gsanim)
        QtCore.QObject.connect(self.bf_anim, QtCore.SIGNAL("clicked()"), self.bfanim)
        QtCore.QObject.connect(self.sin_anim, QtCore.SIGNAL("clicked()"), self.sinanim)
        QtCore.QMetaObject.connectSlotsByName(edumat)
        edumat.setTabOrder(self.scc_tut, self.scc_anim)
        edumat.setTabOrder(self.scc_anim, self.bcc_tut)
        edumat.setTabOrder(self.bcc_tut, self.bcc_anim)
        edumat.setTabOrder(self.bcc_anim, self.fcc_tut)
        edumat.setTabOrder(self.fcc_tut, self.fcc_anim)
        edumat.setTabOrder(self.fcc_anim, self.roll_tut)
        edumat.setTabOrder(self.roll_tut, self.roll_anim)
        edumat.setTabOrder(self.roll_anim, self.fhm_tut)
        edumat.setTabOrder(self.fhm_tut, self.fhm_anim)
        edumat.setTabOrder(self.fhm_anim, self.de_tut)
        edumat.setTabOrder(self.de_tut, self.de_anim)
        edumat.setTabOrder(self.de_anim, self.ie_tut)
        edumat.setTabOrder(self.ie_tut, self.ie_anim)
        edumat.setTabOrder(self.ie_anim, self.f_tut)
        edumat.setTabOrder(self.f_tut, self.f_anim)
        edumat.setTabOrder(self.f_anim, self.gs_tut)
        edumat.setTabOrder(self.gs_tut, self.gs_anim)
        edumat.setTabOrder(self.gs_anim, self.bf_tut)
        edumat.setTabOrder(self.bf_tut, self.bf_anim)
        edumat.setTabOrder(self.bf_anim, self.sin_tut)
        edumat.setTabOrder(self.sin_tut, self.sin_anim)

    def scctut(self):
        self.textBrowser.clear()
        self.textBrowser.setHtml("Tutorial of SCC")

    def bcctut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of BCC")

    def fcctut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of FCC")

    def rolltut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of Rolling")

    def fhmtut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of Four High Mill")

    def detut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of Direct Extrusion")

    def ietut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of Indirect Extrusion")

    def ftut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of Forging")

    def gstut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of Gating System")

    def bftut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of Blast Furnace")

    def sintut(self):
        self.textBrowser.clear()
        self.textBrowser.setText("Tutorial of Sintering")

    def retranslateUi(self, edumat):
        edumat.setWindowTitle(QtGui.QApplication.translate("edumat", "EduMat", None, QtGui.QApplication.UnicodeUTF8))
        edumat.setToolTip(QtGui.QApplication.translate("edumat", "EduMat", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("edumat", "Metallurgy Concepts: Models and process animations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("edumat", "Crystal Structure:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("edumat", "SCC", None, QtGui.QApplication.UnicodeUTF8))
        self.scc_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.scc_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.bcc_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.fcc_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("edumat", "BCC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("edumat", "FCC", None, QtGui.QApplication.UnicodeUTF8))
        self.fcc_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.bcc_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("edumat", "Forming Processes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("edumat", "Rolling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("edumat", "Four High Mill", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("edumat", "Direct Extrusion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("edumat", "Indirect Extrusion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("edumat", "Forging", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("edumat", "Foundry Processes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("edumat", "Gating System", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("edumat", "Iron Making Processes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("edumat", "Blast Furnace", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("edumat", "Sintering", None, QtGui.QApplication.UnicodeUTF8))
        self.ie_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.de_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.fhm_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.roll_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.f_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.gs_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.bf_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.sin_tut.setText(QtGui.QApplication.translate("edumat", "Tutorial ", None, QtGui.QApplication.UnicodeUTF8))
        self.roll_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.fhm_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.de_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.ie_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.f_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.gs_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.bf_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.sin_anim.setText(QtGui.QApplication.translate("edumat", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.marker.setText(QtGui.QApplication.translate("edumat", "Marker Control", None, QtGui.QApplication.UnicodeUTF8))
        self.leave.setText(QtGui.QApplication.translate("edumat", "Leave EduMat", None, QtGui.QApplication.UnicodeUTF8))

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    edumat = QtGui.QDialog()
    ui = Ui_edumat()
    ui.setupUi(edumat)
    edumat.show()
    sys.exit(app.exec_())
